# File: .github/workflows/main-workflow.yml

name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    uses: RahulRawatdevops/reusable_workflow/.github/workflows/main.yml@main
